# Generated by Django 6.0.6 on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('kassa', '0002_cashsession_unique_open_cash_session_per_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='delivery_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transaction', to='delivery.deliveryorder'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transaction', to='restaurant.order'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(order__isnull=False, delivery_order__isnull=True)
                    | models.Q(order__isnull=True, delivery_order__isnull=False)
                ),
                name='cash_transaction_has_one_order_source',
            ),
        ),
    ]
