# Generated by Django 6.0.6 on 2026-07-15 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order_debt_amount_order_is_paid_order_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stol',
                'verbose_name_plural': 'Stollar',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'afitsant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('credit', 'Qarz')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.restauranttable'),
        ),
    ]
