# Generated by Django 6.0.6 on 2026-07-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restauranttable_order_closed_at_order_waiter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restauranttable',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='restaurant.category'),
        ),
    ]
