# Generated by Django 6.0.6 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Admin'),
                    ('oshpaz', 'Oshpaz'),
                    ('kassir', 'Kassir'),
                    ('afitsant', 'Afitsant'),
                    ('farrosh', 'Farrosh'),
                    ('moykachi', 'Moykachi'),
                    ('kuryer', 'Kuryer'),
                    ('customer', 'Customer'),
                ],
                default='customer',
                max_length=20,
            ),
        ),
    ]
