# Generated by Django 6.0.6 on 2026-07-15 13:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0005_restauranttable_order_closed_at_order_waiter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('experience_bonus_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='waiter_kpi', to='restaurant.order')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_records', to='restaurant.restauranttable')),
                ('waiter', models.ForeignKey(limit_choices_to={'role': 'afitsant'}, on_delete=django.db.models.deletion.PROTECT, related_name='kpi_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Afitsant KPI',
                'verbose_name_plural': 'Afitsant KPI lari',
                'ordering': ['-business_date', '-id'],
                'indexes': [models.Index(fields=['waiter', 'business_date'], name='kpi_waiterk_waiter__92125c_idx'), models.Index(fields=['business_date', 'table'], name='kpi_waiterk_busines_ba6dc1_idx')],
            },
        ),
    ]
